version: '3.7'

services:
  rag_chromadb:
    container_name: rag_chromadb
    image: chromadb/chroma
    ports:
      - 8000:8000
    volumes:
      - ./data/.chroma:/chroma/chroma  # Relative path with ./ prefix
    environment:
      IS_PERSISTENT: "true"
      ANONYMIZED_TELEMETRY: "true"
    networks:
      - rag_default

networks:
  rag_default:
    name: rag_default
